seed_everything: 0
optimizer: 
  class_path: torch.optim.AdamW
  init_args:
    lr: 0.0001 # Slightly lower LR for Transformer stability
    weight_decay: 0.05

model:
  class_path: models.SwinFireModel.SwinFireModel
  init_args:
    n_channels: 40
    flatten_temporal_dimension: false
    pos_class_weight: 236 
    loss_function: "Dice"
    hidden_dim: 96
    required_img_size: [128, 128]

do_train: true
do_test: true